### ISSUE TITLE
NEWPIPE_HISTORY_DB Evirement variable doesn't exist

### ISSUE THREAD

**Issue by madbehaviorus** [iamtalhaasghar/newpipe-to-freetube-history-sync#1]
I don't know from witch case you start.
But the NEWPIPE_HISTORY_DB Environment variable doesn't exists on a normal installed linux.
It gives the following error:

`expected str, bytes or os.PathLike object, not NoneType`

If I change the line 

`conn = sqlite3.connect(os.getenv('NEWPIPE_HISTORY_DB'))` 

to 

`conn = sqlite3.connect($fully_path_to_the_file) `

and run it again, it works.

Thank you.

**Comment by iamtalhaasghar** [comment]
You can read more about how enviornment variables work form [here](https://www.telerik.com/blogs/beginners-guide-environment-variables). 

P.S: I'm not affiliated with the blog in any regard. I just did a google search and pasted the very first link here for you. Enjoy :)

**Comment by madbehaviorus** [comment]
@ imatalhaasghar
This is not an answer about my sentences from above...
An undefined variable is an undefined variable.

**Comment by iamtalhaasghar** [comment]
You have to define it yourself in an `.env` file or in current shell enviornment using `export NEW_PIPE_DB=/path/to/db`. @madbehaviorus
